### ISSUE TITLE
Issue with accents

### ISSUE THREAD

**Issue by dacasine** [westh/alfred-guru-workflow#1]
Hi :)

Before explaining the issue, let me say that I am soooo happy that you developped this :). A huge thank you.

If we search anything with foreign accents, we have the following error : 

Error in workflow 'Guru'
cannot concatenate 'str' and 'list' objects

Thanks again for your job

**Comment by westh** [comment]
👋 Hi there,

You're right. I've fixed it in [version 1.0.1](https://github.com/westh/alfred-guru-workflow/releases/tag/1.0.1). Seems to be a fairly common problem: https://www.alfredforum.com/topic/7357-encoding-in-script-filter-input/.

Glad that you like the workflow.

**Comment by dacasine** [comment]
Thank you very much, @westh  :) it works well. Any way to offer you a coffee ?

**Comment by westh** [comment]
@dacasine now there is : )

<img width="813" alt="image" src="https://user-images.githubusercontent.com/7045079/154709565-8a664cd2-d5a2-4ba1-befa-ce84b80c2419.png">
